name: Build and Deploy to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-artifact: next-build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile=false

      - name: Build
        run: pnpm build

      - name: Archive production artifact
        run: |
          mkdir -p deploy
          cp -r .next package.json next.config.ts deploy/
          cp -r public deploy/public
          cp -r node_modules deploy/node_modules || true
          # App Service will run `npm start`; ensure script exists
          # (we rely on next start)
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: deploy

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: next-build
          path: .

      - name: Generate minimal web.config for Linux (noop)
        run: echo "ok"

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .