name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [main]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
          lfs: false

      # Pin Node for Oryx/SWA build and SSR runtime compatibility
      - name: Set Node version for SWA
        run: echo "NODE_VERSION=20" >> $GITHUB_ENV

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_STONE_038C65803 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: "/"       # project root
          api_location: ""        # no Functions
          output_location: ""     # IMPORTANT: leave empty for Next.js
          node_version: "20"      # <- explicit pin for the action/Oryx
          app_build_command: "npm run build"
        env:
          # Your frontend needs this at runtime
          NEXT_PUBLIC_API_BASE: "https://finance-agent.politepebble-62c55b82.swedencentral.azurecontainerapps.io"
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_STONE_038C65803 }}
          action: close
